install.packages("Rcmdr", dependencies = TRUE)
library(Rcmdr)
read.table("RMR_Results.csv", header=TRUE, stringsAsFactors=TRUE, sep=",", na.strings="NA", dec=".", strip.white=TRUE)
editDataset(Dataset)
Dataset <- within(Dataset, { day <- as.factor(day)})
Dataset <- within(Dataset, {pco2 <- as.factor(pco2)})
Anova <- lm(rmr ~day*pco2, data=Dataset, contrasts=list(day="contr.Sum", pco2="cntr.Sum"))
Install.packages("compute.es")
##Anova, not that lm is an anova really, aov is an lm in anova package, out puts the same
DataModel<-lm(rmr~pco2, data = Dataset)
newModel<-aov(rmr~pco2, data= Dataset,na.action=na.exclude)
## ANCOVA jsut add covariate to lm or aov
DataModel<-lm(rmr~pco2 + day, data = Dataset)
summary(newModel)
summary(DataModel)
leveneTest(Dataset$rmr, Dataset$mass, center=median)
