---
title: "Muusoctopus leioderma respiration"
author: "Lloyd Trueblood and Kirt Onthank"
date: "9/23/2021"
output: pdf_document
---

# Reading in libraries
```{r}
library(OTools)
library(xlsx)
```

# Find the relevant files
```{r}
files=list.files(recursive=T)
resp.files=grep(".txt",files,value=T)
pcrit.files=grep("pcrit|pcrti",resp.files,value=T,ignore.case=T)
rmr.files=setdiff(resp.files,pcrit.files)
```

```{r}
grep("blank",resp.files,value=T,ignore.case=T)
```


# Reading in the data log xlsx file
```{r}
data.log=read.xlsx("Muus Data Log.xlsx",sheetIndex = 1)
```

# Running the RMR data analysis
First I am going to make a object to put the RMR data into
```{r}
routine=data.frame(filename=as.character(),spreadsheet_guess=as.character(),mass=as.numeric(),pco2=as.numeric(),rmr=as.numeric())
```



```{r}
column.count=1
for (i in 1:length(rmr.files)){
  filename=rmr.files[i]
  print(paste("starting file ", basename(filename)," (loop",i,")",sep=""))
  if(length(grep("Group 4|presens|ch\\d\\.txt",filename))>0){
    resp=read.presens(filename)
  }else{
    resp=read.pyro(filename)
  }
  print("finding closest match in log")

guess=which.min(adist(basename(filename),data.log$File.name))
  
    flow=as.numeric(data.log$flow.rate..L.min.[guess])
    mass=as.numeric(data.log$Mass..g.[guess])
    if(is.na(flow)){
      flow=0.1
    }
    if(is.na(mass)){
      mass=10
    }
    print("calculating rmr")
    resp.mean=mean(resp.open(resp[resp$times>3600,],flow.rate=flow*1000,weight=mass)$resp)
    print("writing data to object")
    routine[column.count,1]=basename(filename)
    routine[column.count,2]=data.log$File.name[guess]
    routine[column.count,3]=mass

    if(length(grep("1800",filename))>0){
     routine[column.count,4]=1800
    }
    if(length(grep("1000",filename))>0){
      routine[column.count,4]=1000
    }
    routine[column.count,5]=resp.mean
    column.count=column.count+1
    if(sum(is.na(resp$O23))<10){
      print("found second respirometer")
      resp.mean=mean(resp.open(resp[resp$times>3600,],inflow=3,outflow=4,flow.rate=flow*1000,weight=mass)$resp)
      print("writing data to object")
      routine[column.count,1]=basename(filename)
      routine[column.count,2]=data.log$File.name[guess]
      routine[column.count,3]=mass
  
      if(length(grep("1800",filename))>0){
       routine[column.count,4]=1800
      }
      if(length(grep("1000",filename))>0){
        routine[column.count,4]=1000
      }
      routine[column.count,5]=resp.mean
      column.count=column.count+1
    }
  print(paste("end of file ", basename(filename)," (loop",i,")",sep=""))
}



```


```{r}
write.xlsx(routine,"RMR_Results.xlsx")
```

