---
title: "Pcrit Run Evaluation"
author: "Kirt L Onthank"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(OTools)
library(respirometry)
library(knitr)
library(nlme)
library(car)
```

```{r}
files=list.files(recursive=T)
resp.files=grep(".txt",files,value=T)
pcrit.files=grep("pcrit|pcrti",resp.files,value=T,ignore.case=T)
pcrit.files=pcrit.files[!duplicated(basename(pcrit.files))]

pcrit.files.read=pcrit.files[!grepl("ch2.txt|ch3.txt|ch4.txt|\\(1\\).txt",pcrit.files)]
write.csv(basename(pcrit.files.read),file = "pcrit_read_log.csv")
pcrit.files.read
```


```{r}
pcrit.log=read.csv("pcrit_log.csv")
routine=read.csv("RMR_Results.csv")
```


```{r}
pcrits=data.frame(filename=as.character(),spreadsheet_guess=as.character(),octo=as.character(),mass=as.numeric(),pco2=as.numeric(),day=as.numeric(),rmr=as.numeric(),pcrit=as.numeric())

```


```{r warning=FALSE}
co=1

for (i in 1:length(pcrit.files.read)){
  filename=pcrit.files.read[i]  

  if(length(grep("Group 4|presens|ch\\d\\.txt",basename(filename)))>0){
    pcrit.raw=read.presens(filename)
  }else{
    pcrit.raw=read.pyro(filename)
  }

guess=which.min(adist(basename(filename),pcrit.log$filename))  
ch=pcrit.log$ch1[guess]
octo=pcrit.log$octo1[guess]
start=pcrit.log[guess,6+ch]
stop=max(pcrit.raw$times)-pcrit.log[guess,10+ch]
mass=mean(routine$mass[routine$octo==octo])
rmr=mean(routine$rmr[routine$octo==octo])
  
pcrit.working=
  pcrit.raw[
    pcrit.raw$times>start&
    pcrit.raw$times<stop,
  ]
vol=pcrit.log$vol[guess]
drop.time=round((stop-start)/3600,1)
O2.drop=round(diff(range(pcrit.working[,3+ch])),1)
rough.mo2=round((O2.drop*vol)/mass/drop.time,1)

plot(pcrit.raw[,3+ch]~pcrit.raw$times,type="l",main=basename(filename))
points(pcrit.working[,3+ch]~pcrit.working$times,type="l",col="red")
mtext(paste("mass=",mass),side=3,adj=1,line=-1)
mtext(paste0("resp vol=",vol),side=3,adj=1,line=-2)
mtext(paste0("drop time=",drop.time," hr"),side=3,adj=1,line=-3)
mtext(paste0("O2 drop=",O2.drop),side=3,adj=1,line=-4)
mtext(paste0("rough mean MO2=",rough.mo2),side=3,adj=1,line=-5)

pcrit.resp=resp.closed(pcrit.working,volume=pcrit.log$vol[guess],
            weight=mass,smooth="loess",channel=ch,smooth.span = 0.2)

pcrit.bin=aggregate(pcrit.resp$resp~round(pcrit.resp$po2,1),FUN="mean")
colnames(pcrit.bin)=c("po2","resp")

if(max(pcrit.bin$resp)>rmr){
  plot_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3,MR=rmr)   
}else{
  plot_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3)
}


pcrits[co,1]=basename(filename)
pcrits[co,2]=pcrit.log$filename[guess]
pcrits[co,3]=octo
pcrits[co,4]=mass
pcrits[co,5]=pcrit.log$pco2[guess]
pcrits[co,6]=pcrit.log$day[guess]
pcrits[co,7]=rmr
if (min(pcrit.working[,3+ch])<50){
  if(max(pcrit.bin$resp)>rmr){
  pcrits[co,8]=as.numeric(calc_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3,MR=rmr)[1])
  }else{
    pcrits[co,8]=as.numeric(calc_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3)[1])
  }
}else{
  pcrits[co,8]=NA
}
co=co+1

if(!is.na(pcrit.log$ch2[guess])){
  ch=pcrit.log$ch2[guess]
  octo=pcrit.log$octo2[guess]
  start=pcrit.log[guess,6+ch]
  stop=max(pcrit.raw$times)-pcrit.log[guess,10+ch]
  mass=mean(routine$mass[routine$octo==octo])
  rmr=mean(routine$rmr[routine$octo==octo])
  
  pcrit.working=
    pcrit.raw[
      pcrit.raw$times>start&
      pcrit.raw$times<stop,
    ]

  plot(pcrit.raw[,3+ch]~pcrit.raw$times,type="l",main=basename(filename))
  points(pcrit.working[,3+ch]~pcrit.working$times,type="l",col="red")

  pcrit.resp=resp.closed(pcrit.working,volume=pcrit.log$vol[guess],
            weight=mass,smooth="loess",channel=ch,smooth.span = 0.2)
  pcrit.bin=aggregate(pcrit.resp$resp~round(pcrit.resp$po2,1),FUN="mean")
  colnames(pcrit.bin)=c("po2","resp")

  plot_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3,MR=rmr) 

  pcrits[co,1]=filename
  pcrits[co,2]=pcrit.log$filename[guess]
  pcrits[co,3]=octo
  pcrits[co,4]=mass
  pcrits[co,5]=pcrits$pco2[guess]
  pcrits[co,6]=pcrits$day[guess]
  pcrits[co,7]=rmr
  if (min(pcrit.working[,3+ch])<50){
    if(max(pcrit.bin$resp)>rmr){
    pcrits[co,8]=as.numeric(calc_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3,MR=rmr)[1])
    }else{
      pcrits[co,8]=as.numeric(calc_pcrit(pcrit.bin$po2,pcrit.bin$resp,
           avg_top_n = 3)[1])
    }
  }else{
    pcrits[co,8]=NA
  }
  co=co+1
  
}


}





```
```{r}
pcrits=pcrits[complete.cases(pcrits),]
pcrits=pcrits[pcrits$filename!="GR1 Muus1000 pcrit 7-21-21.txt",]
```


```{r}
plot(pcrit~mass,data=pcrits)
```


```{r}
aggregate(pcrit~pco2+day,data=pcrits,FUN="length")
```

## setting pCO2 to factor class:
```{r short_input}
pcrits$pco2=as.factor(pcrits$pco2)
```

## Next I set orthogonal contrasts:
```{r short_contrast}
contrasts(pcrits$pco2)=contr.poly(2) 
```

```{r}
aggregate(pcrit~day+octo,data=pcrits,FUN="length")
```


## Running the linear mixed effects model and ANOVA using type III sum of squares:
```{r linear mixed effects model}
pcrits.lme=lme(pcrit~mass+pco2+day,random=~1|octo,
             correlation=corAR1(form=~day|octo),
              data=pcrits,na.action=na.omit)

Anova(pcrits.lme,type="III")
```
## Plotting the lme results


```{r}
boxplot(pcrit~day+pco2,data=pcrits,range=0)
```


